"""
Spike 0.5.1: Validate faster-whisper integration.

Usage:
    python faster_whisper_test.py <video_file> [--model-path PATH]

Requires:
    - faster-whisper (pip install faster-whisper)
    - ffmpeg on PATH
    - psutil (pip install psutil)

If the model can't be downloaded (e.g., HuggingFace blocked by firewall),
use --model-path to point to a pre-downloaded CTranslate2 model directory.
Download from: https://huggingface.co/Systran/faster-whisper-base/tree/main
"""

import argparse
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import psutil
from faster_whisper import WhisperModel


def extract_audio(video_path: Path, audio_path: Path) -> float:
    """Extract audio from video using ffmpeg. Returns duration in seconds."""
    cmd = [
        "ffmpeg", "-i", str(video_path),
        "-vn", "-acodec", "pcm_s16le", "-ar", "16000", "-ac", "1",
        "-y", str(audio_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ffmpeg error:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)

    probe_cmd = [
        "ffprobe", "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(video_path),
    ]
    probe_result = subprocess.run(probe_cmd, capture_output=True, text=True)
    return float(probe_result.stdout.strip())


def format_timestamp(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    if h > 0:
        return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"


def transcribe(audio_path: Path, model_ref: str) -> tuple[list[dict], float]:
    """Transcribe audio file. Returns (segments, elapsed_seconds)."""
    print(f"Loading model '{model_ref}' (CPU)...")
    model = WhisperModel(model_ref, device="cpu", compute_type="int8")

    print("Transcribing...")
    process = psutil.Process()
    mem_before = process.memory_info().rss / (1024 * 1024)

    start = time.perf_counter()
    segments_iter, info = model.transcribe(str(audio_path), beam_size=5)

    segments = []
    for segment in segments_iter:
        segments.append({
            "start": segment.start,
            "end": segment.end,
            "text": segment.text.strip(),
        })

    elapsed = time.perf_counter() - start
    mem_after = process.memory_info().rss / (1024 * 1024)

    print(f"Detected language: {info.language} (probability {info.language_probability:.2f})")
    print(f"Memory usage: {mem_before:.0f} MB -> {mem_after:.0f} MB (delta: {mem_after - mem_before:.0f} MB)")

    return segments, elapsed


def generate_markdown(segments: list[dict], video_name: str) -> str:
    lines = [
        f"# Transcript: {video_name}",
        "",
        f"*Generated by faster-whisper (base model, CPU)*",
        "",
        "---",
        "",
    ]
    for seg in segments:
        ts = format_timestamp(seg["start"])
        lines.append(f"**[{ts}]** {seg['text']}")
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Spike 0.5.1: faster-whisper validation")
    parser.add_argument("video_file", help="Path to a video file")
    parser.add_argument(
        "--model-path",
        help="Path to a pre-downloaded CTranslate2 model directory "
             "(use if HuggingFace download is blocked)",
    )
    args = parser.parse_args()

    video_path = Path(args.video_file)
    if not video_path.exists():
        print(f"File not found: {video_path}", file=sys.stderr)
        sys.exit(1)

    model_ref = args.model_path if args.model_path else "base"

    print(f"=== Spike 0.5.1: faster-whisper validation ===")
    print(f"Input: {video_path}")
    print(f"Model: {model_ref}")
    print()

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        audio_path = Path(tmp.name)

    print("Extracting audio with ffmpeg...")
    duration = extract_audio(video_path, audio_path)
    print(f"Audio duration: {format_timestamp(duration)} ({duration:.1f}s)")
    print()

    try:
        segments, elapsed = transcribe(audio_path, model_ref)
    except Exception as e:
        error_msg = str(e)
        if "SSL" in error_msg or "ConnectError" in error_msg or "LocalEntryNotFoundError" in error_msg:
            print(f"\nERROR: Cannot download model — network issue: {error_msg[:100]}")
            print()
            print("HuggingFace appears to be blocked on this network.")
            print("Workaround: download the model on an unrestricted network and use --model-path:")
            print()
            print("  1. On another machine: pip install huggingface_hub")
            print("  2. python -c \"from huggingface_hub import snapshot_download; "
                  "snapshot_download('Systran/faster-whisper-base', local_dir='./faster-whisper-base')\"")
            print("  3. Copy the folder here, then run:")
            print(f"     python faster_whisper_test.py {video_path} --model-path ./faster-whisper-base")
            audio_path.unlink(missing_ok=True)
            sys.exit(1)
        raise
    print()

    rtf = elapsed / duration if duration > 0 else float("inf")
    print(f"=== Results ===")
    print(f"Segments produced: {len(segments)}")
    print(f"Transcription time: {elapsed:.1f}s")
    print(f"Real-time factor: {rtf:.2f}x (target: < 2.0x)")
    print(f"Go/No-go: {'GO' if rtf < 2.0 else 'NO-GO'} (RTF {'<' if rtf < 2.0 else '>='} 2.0x)")
    print()

    output_path = video_path.with_suffix(".transcript.md")
    md = generate_markdown(segments, video_path.name)
    output_path.write_text(md, encoding="utf-8")
    print(f"Markdown output written to: {output_path}")

    audio_path.unlink(missing_ok=True)

    print()
    print("=== Sample output (first 10 segments) ===")
    for seg in segments[:10]:
        ts = format_timestamp(seg["start"])
        print(f"  [{ts}] {seg['text'][:80]}")


if __name__ == "__main__":
    main()
