"""add class_id indexes and wiki_pages path unique constraint

Revision ID: af54031e5fdb
Revises: 5319f420035a
Create Date: 2026-08-09 16:26:58.239706

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af54031e5fdb"
down_revision: str | Sequence[str] | None = "5319f420035a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_messages_class_id"), ["class_id"], unique=False)

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_files_class_id"), ["class_id"], unique=False)

    with op.batch_alter_table("wiki_pages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_wiki_pages_class_id"), ["class_id"], unique=False)
        batch_op.create_unique_constraint("uq_wiki_pages_class_id_path", ["class_id", "path"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wiki_pages", schema=None) as batch_op:
        batch_op.drop_constraint("uq_wiki_pages_class_id_path", type_="unique")
        batch_op.drop_index(batch_op.f("ix_wiki_pages_class_id"))

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_class_id"))

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_class_id"))

    # ### end Alembic commands ###
